# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-26 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
