# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-26 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='axiologe_project',
            new_name='axiologue_project',
        ),
    ]
