# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-26 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170125_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='list_order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
