# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-26 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_list_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='list_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
